package Counter;


/**
* Counter/Count.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Count.idl
* Wednesday, February 19, 2014 9:35:29 AM IST
*/

public interface Count extends CountOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Count
