package Counter;


/**
* Counter/CountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Count.idl
* Wednesday, February 19, 2014 9:35:29 AM IST
*/

public interface CountOperations 
{
  int sum ();
  void sum (int newSum);
  int increment ();
} // interface CountOperations
