package Counter;


/**
* Counter/CountPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Count.idl
* Wednesday, February 19, 2014 10:00:24 PM IST
*/

public class CountPOATie extends CountPOA
{

  // Constructors

  public CountPOATie ( Counter.CountOperations delegate ) {
      this._impl = delegate;
  }
  public CountPOATie ( Counter.CountOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public Counter.CountOperations _delegate() {
      return this._impl;
  }
  public void _delegate (Counter.CountOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public int sum ()
  {
    return _impl.sum();
  } // sum
  public void sum (int newSum)
  {
    _impl.sum(newSum);
  } // sum

  public int increment ()
  {
    return _impl.increment();
  } // increment

  private Counter.CountOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class CountPOATie
